### ISSUE TITLE
GMail integration processes emails in reverse (newest-first) order)

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-circuit-maintenance#122]
### Environment

- Python version: 
- Nautobot version: 
- nautobot-circuit-maintenance version: 

### Expected Behavior

Emails to be processed in chronological order

### Observed Behavior

Emails are processed in reverse chronological order - newest first, oldest last. This has the consequence that the terminal state of any CircuitMaintenance that has multiple emails will be that of the *oldest* update, instead of the *newest* update as it should be.

### Steps to Reproduce

1.
2.
3.

**Comment by dgarros** [comment]
At first glance it sounds surprising that the order in which we are processing the emails as an impact on the status of the maintenance
Could we, if we aren't already doing it, check the time of the last update received and only apply changes for newer notifications ?

**Comment by chadell** [comment]
I believe that the best approach is a combination of both points:
- The fix proposed by @glennmatthews has all the sense, because this way we will got the sequence of events in a Maintenance
- And the point suggested by @dgarros is not implemented yet, but was planned, so taking the `stamp` from a Maintenance, we should **ignore** any update that is older that the previous one

**Comment by chadell** [comment]
I'm finding some issues with the sorting, because the `list` method only returns the`message.id` and `message.treadid` and the there is no actual order, it's random: https://stackoverflow.com/questions/43072057/gmail-api-is-there-a-way-to-list-messages-in-sorted-order-w-r-t-receive-time
So, what I'm thinking is to not focus on ordering the notificaitons, and go directly to the second point, so we will take all the notifications into account but only update the state of the maitenance for the newer ones, so we will have the full story of notifications but keeping the latest state.

**Comment by chadell** [comment]
Fixed in #123
