### ISSUE TITLE
"since" filter is too coarse-grained

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-circuit-maintenance#46]
### Environment

- Python version: 
- Nautobot version: 
- nautobot-circuit-maintenance version: 

### Expected Behavior

Running the job should pick up all emails that arrived since the last time the job was run

### Observed Behavior

Because the `since` filtering is date-based (not date-time based), any emails that arrived during the same day as the last job run will be skipped over, even though they haven't been processed yet.

### Steps to Reproduce

1.
2.
3.

**Comment by glennmatthews** [comment]
Maybe filtering by read/unread status might be a viable alternative?

**Comment by chadell** [comment]
I've been investigating this, and the goal of the SINCE filter was to limit the emails read to only do it once.
You are right on the observation about SINCE not being good enough for a periodic fetch of notifications, and I agree with you that a viable option, either for IMAP and Gmail API, would be to use the SEEN/UNSEEN flag to retrieve only the UNSEEN and to mark a email as SEEN after being processed.

**Comment by chadell** [comment]
implemented in #53
